// 81. Write a JavaScript program to create an object with keys generated by running the provided function for each key and the same values as the provided object.

const iterateOverKeys = (obj, callbackFN) => Object.entries(obj).reduce((accumulator, value, valueIndex, originalArray) => {accumulator[callbackFN(value[0])]=value[1]; return acc},{});

let addSomething = (value) => `SECONDARY_KEY_${value}`;
let user = {
    age: 5,
    name: "David"
};

console.log(iterateOverKeys(user, addSomething));