// 84. Write a JavaScript program to create an object with the same keys as the provided object and values generated by running the provided function for each value.

let iterateOver_KVP = (obj, callback_FN) => Object.entries(obj).reduce((accumulator, value, valueIndex, originalArray) => { accumulator[value[0]] = callback_FN.call(null, value[1]) ; return accumulator;}, {})

let pow = (value) => Math.pow(value, 2);
let obj = {
    first: 1,
    second: 2,
    third: 3,
    fourth: 4,
    fifth: 5
};

console.log(iterateOver_KVP(obj, pow));